include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v3/common.yml'

.projecttest:
  extends: .test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH
    - julia --project=$CI_JULIA_PROJECT -e '
                          using Pkg;
                          Pkg.resolve();
                          Pkg.instantiate();
                          Pkg.build();
                          include("test/runtests.jl");'
.cudagputest:
  extends: .projecttest
  variables:
    CI_IMAGE_TAG:     'cuda'
    CI_JULIA_PROJECT: 'test/CUDA/gpuenv'
  tags:
    - cuda

.rocmgputest:
  extends: .projecttest
  variables:
    CI_IMAGE_TAG:     'rocm'
    CI_JULIA_PROJECT: 'test/ROC/gpuenv'
  tags:
    - rocm

.cputest:
  extends: .projecttest
  variables:
    CI_IMAGE_TAG:     'plain'
    CI_JULIA_PROJECT: 'test/testenv'

cudagpu:test:dev:
  extends: .cudagputest
  variables:
    CI_VERSION_TAG: 'dev'
  allow_failure: true

rocmgpu:test:dev:
  extends: .rocmgputest
  variables:
    CI_VERSION_TAG: 'dev'
  allow_failure: true

cpu:test:dev:
  extends: .cputest
  variables:
    CI_VERSION_TAG: 'dev'
  allow_failure: true

cudagpu:test:v1.1:
  extends: .cudagputest
  variables:
    CI_VERSION_TAG: 'v1.1'

rocmgpu:test:v1.1:
  extends: .rocmgputest
  variables:
    CI_VERSION_TAG: 'v1.1'

cpu:test:v1.1:
  extends: .cputest
  variables:
    CI_VERSION_TAG: 'v1.1'

documentation:
  extends: .documentation
  dependencies:
    - cpu:test:v1.1 
  variables:
    CI_VERSION_TAG: 'v1.1'
    CI_IMAGE_TAG: 'plain'
  only:
    - master
    - staging
    - trying

pages:
  dependencies:
    - documentation
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master

